# Generated by Django 4.1.3 on 2022-11-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(default="testslug"),
        ),
    ]
