# Generated by Django 4.1.3 on 2022-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(default="testslug", unique=True),
        ),
    ]
